---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
    anonymous:
    enabled: false
    webhook:
    cacheTTL: 2m0s
    enabled: true
    x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
    mode: Webhook
    webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: systemd
cgroupsPerQOS: true
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
evictionSoft:
    memory.available: "10%"
    nodefs.available: "15%"
    nodefs.inodesFree: "10%"
    imagefs.available: "20%"
evictionSoftGracePeriod:
    memory.available: "2m"
    nodefs.available: "2m"
    nodefs.inodesFree: "2m"
    imagefs.available: "2m"
evictionHard:
    memory.available: "5%"
    nodefs.available: "10%"
    nodefs.inodesFree: "5%"
    imagefs.available: "15%"
# Setting reserved resources will decrease the ammount of allocatable resources for each node:
# Here is the formula:
# [Allocatable] = [Node Capacity] - [kube-reserved] - [system-reserved] - [Hard-Eviction-Thresholds]
kubeReserved:
    cpu: "250m"
systemReserved:
    cpu: "250m"