- hosts: workers
  tasks:
    - name: Basic Setup
      import_tasks: roles/common/main.yml
    - name: Worker Setup
      import_tasks: roles/worker/main.yml
  handlers:
    - name: docker status
      service: name=docker state=started
