---
- name: Initialize the Kubernetes cluster using kubeadm
  become: yes
  command: kubeadm init --v=5 --pod-network-cidr 10.244.0.0/16
- name: Create the .kube directory
  file: "path={{ ansible_env.HOME }}/.kube state=directory"
- name: Setup kubeconfig for vagrant user
  become: true
  copy:
    dest: "{{ ansible_env.HOME }}/.kube/config"
    src: /etc/kubernetes/admin.conf
    remote_src: true

# Step 2.5: Setup the kube config file for the user to access the Kubernetes cluster using the below code.
# - name: Setup kubeconfig for vagrant user
#   command: "{{ item }}"
#   with_items:
#   - echo $(pwd) && exit 1 
#   - mkdir -p $(pwd)/.kube
#   - sudo cp -i /etc/kubernetes/admin.conf $(pwd)/.kube/config
#   - chown $(whoami):$(whoami) $(pwd)/.kube/config
# Step 2.6: Setup the container networking provider and the network policy engine using the below code.
- name: Install calico pod network
  command: "kubectl --kubeconfig={{ ansible_env.HOME }}/.kube/config create -f https://raw.githubusercontent.com/coreos/flannel/v0.12.0/Documentation/kube-flannel.yml"
- name: Copy kubectl file to local-box
  become: true
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./kubectl_config
# Step 2.8: Setup a handler for checking Docker daemon using the below code.
# - name: setup handler
#   handlers:
#     - name: docker status
#       service: name=docker state=started
